name: test

on:
  pull_request:
    branches:
      - main

env:
  FOUNDRY_PROFILE: ci

jobs:
  forge-test:
    name: Run Forge Tests and Checks 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Install eth-abi
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install eth-abi

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes
        id: build

      - name: Run Forge tests
        run: |
          forge test -vvv --ffi
        id: test

      - name: Check formatting
        run: |
          forge fmt --check
        id: fmt
